//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arc : Page
    {
        public Nullable<int> CurrentDateId { get; set; }
        public Nullable<int> StartDateId { get; set; }
    
        public virtual GameDate CurrentGameDate { get; set; }
        public virtual GameDate StartGameDate { get; set; }
    }
}
