//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class AwardNomination
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int TrophyId { get; set; }
        public string NominationReason { get; set; }
        public string RejectedReason { get; set; }
        public string AcceptedReason { get; set; }
        public Nullable<System.DateTime> AwardedOn { get; set; }
        public Nullable<System.DateTime> RejectedOn { get; set; }
        public Nullable<int> NominatedById { get; set; }
        public Nullable<System.DateTime> NominatedDate { get; set; }
        public int CampaignId { get; set; }
        public bool IsPrivate { get; set; }
        public Nullable<int> AwardId { get; set; }
        public Nullable<int> SessionId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Player Player { get; set; }
        public virtual Trophy Trophy { get; set; }
        public virtual Award Award { get; set; }
        public virtual Session Session { get; set; }
    }
}
