//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public Book()
        {
            this.BookChapters = new HashSet<BookChapter>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public bool ShowIndex { get; set; }
        public bool IncludeInMenu { get; set; }
    
        public virtual ICollection<BookChapter> BookChapters { get; set; }
    }
}
