//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookChapter
    {
        public BookChapter()
        {
            this.BookPages = new HashSet<BookPage>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
        public Nullable<int> SortOrder { get; set; }
        public int BookId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual ICollection<BookPage> BookPages { get; set; }
    }
}
