//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookPage
    {
        public int Id { get; set; }
        public int BookChapterId { get; set; }
        public int PageId { get; set; }
        public int SortOrder { get; set; }
    
        public virtual BookChapter BookChapter { get; set; }
        public virtual Page Page { get; set; }
    }
}
