//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comment
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public int CreatedById { get; set; }
        public Nullable<int> PersonId { get; set; }
        public int PageId { get; set; }
        public bool IsAdmin { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual Person Person { get; set; }
        public virtual Player Player { get; set; }
    }
}
