//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Creature : Page
    {
        public Creature()
        {
            this.ChildCreatures = new HashSet<Creature>();
            this.CreatureAbilities = new HashSet<CreatureAbility>();
            this.Reputations = new HashSet<Reputation>();
        }
    
        public Nullable<int> ParentType { get; set; }
        public int ThreatLevelId { get; set; }
    
        public virtual ICollection<Creature> ChildCreatures { get; set; }
        public virtual Creature ParentCreature { get; set; }
        public virtual ICollection<CreatureAbility> CreatureAbilities { get; set; }
        public virtual ICollection<Reputation> Reputations { get; set; }
    }
}
