//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExceptionLog
    {
        public int Id { get; set; }
        public int Severity { get; set; }
        public string Message { get; set; }
        public System.DateTime DateTime { get; set; }
        public byte[] Timestamp { get; set; }
        public Nullable<int> UserId { get; set; }
        public string StackTrace { get; set; }
        public string ExceptionType { get; set; }
        public string ExecutingAssembly { get; set; }
        public int Sequence { get; set; }
        public string Identifier { get; set; }
        public Nullable<int> EntityId { get; set; }
    }
}
