//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExperiencePoint
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int PersonId { get; set; }
        public Nullable<int> SessionId { get; set; }
        public Nullable<int> TermId { get; set; }
        public Nullable<int> PersonAttributeId { get; set; }
        public System.DateTime Awarded { get; set; }
        public Nullable<System.DateTime> Spent { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual PersonAttribute PersonAttribute { get; set; }
        public virtual Player Player { get; set; }
        public virtual Session Session { get; set; }
        public virtual Term Term { get; set; }
    }
}
