//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameDate
    {
        public GameDate()
        {
            this.People = new HashSet<Person>();
            this.Sessions = new HashSet<Session>();
            this.Arcs = new HashSet<Arc>();
            this.Arcs1 = new HashSet<Arc>();
        }
    
        public int Id { get; set; }
        public int Year { get; set; }
        public int Month { get; set; }
        public int Day { get; set; }
        public string Comment { get; set; }
    
        public virtual ICollection<Person> People { get; set; }
        public virtual ICollection<Session> Sessions { get; set; }
        public virtual ICollection<Arc> Arcs { get; set; }
        public virtual ICollection<Arc> Arcs1 { get; set; }
    }
}
