//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAttribute
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int PersonAttributeTypeEnum { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int InitialValue { get; set; }
        public int CurrentValue { get; set; }
        public int XpSpent { get; set; }
        public int CampaignId { get; set; }
        public bool IsPrivate { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
