//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place : Page
    {
        public Place()
        {
            this.Child = new HashSet<Place>();
        }
    
        public Nullable<int> IsWithin { get; set; }
        public int PlaceType { get; set; }
    
        public virtual ICollection<Place> Child { get; set; }
        public virtual Place Parent { get; set; }
    }
}
