//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlayerCampaign
    {
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int CampaginId { get; set; }
        public int PlayerModeEnum { get; set; }
    
        public virtual CampaignDetail CampaignDetail { get; set; }
        public virtual Player Player { get; set; }
    }
}
