//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Post
    {
        public int Id { get; set; }
        public int SessionId { get; set; }
        public int PlayerId { get; set; }
        public Nullable<int> CharacterId { get; set; }
        public int PostType { get; set; }
        public string OriginalContent { get; set; }
        public string RevisedContent { get; set; }
        public string TargetPlayerIds { get; set; }
        public System.DateTime DatePosted { get; set; }
        public int DieSize { get; set; }
        public int DieCount { get; set; }
        public int RollType { get; set; }
        public int RollTarget { get; set; }
        public string RollValues { get; set; }
        public bool ReRollMaximums { get; set; }
        public bool IsRevised { get; set; }
        public Nullable<System.DateTime> LastEdited { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public int CampaignId { get; set; }
    
        public virtual Player Player { get; set; }
        public virtual Session Session { get; set; }
    }
}
