//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reputation
    {
        public int Id { get; set; }
        public int WearLevelId { get; set; }
        public int HarmLevelId { get; set; }
        public decimal Xp { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public Nullable<int> PersonId { get; set; }
        public Nullable<int> OrganisationId { get; set; }
        public Nullable<int> CreatureId { get; set; }
    
        public virtual Creature Creature { get; set; }
        public virtual Organisation Organisation { get; set; }
        public virtual Person Person { get; set; }
    }
}
