//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScenePost
    {
        public int Id { get; set; }
        public int SceneId { get; set; }
        public int CharacterId { get; set; }
        public int PlayerId { get; set; }
        public string TextContent { get; set; }
        public System.DateTime DateTime { get; set; }
        public Nullable<System.DateTime> EditedDateTime { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Player Player { get; set; }
        public virtual Scene Scene { get; set; }
    }
}
