//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scene
    {
        public Scene()
        {
            this.ScenePosts = new HashSet<ScenePost>();
        }
    
        public int Id { get; set; }
        public Nullable<int> LeadCharacterId { get; set; }
        public Nullable<int> LocationId { get; set; }
        public System.DateTime DateTime { get; set; }
    
        public virtual Page Page { get; set; }
        public virtual Person Person { get; set; }
        public virtual Place Place { get; set; }
        public virtual ICollection<ScenePost> ScenePosts { get; set; }
    }
}
