//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session : Page
    {
        public Session()
        {
            this.Posts = new HashSet<Post>();
            this.PostOrders = new HashSet<PostOrder>();
            this.SessionLogs = new HashSet<SessionLog>();
            this.Awards = new HashSet<Award>();
            this.AwardNominations = new HashSet<AwardNomination>();
            this.ExperiencePoints = new HashSet<ExperiencePoint>();
        }
    
        public Nullable<System.DateTime> DateTime { get; set; }
        public Nullable<int> Length { get; set; }
        public bool IsClosed { get; set; }
        public bool IsTextSession { get; set; }
        public bool IsPrivate { get; set; }
        public bool IsGmTurn { get; set; }
        public Nullable<System.DateTime> XpAwarded { get; set; }
        public bool GmIsSuspended { get; set; }
        public Nullable<int> GmId { get; set; }
        public Nullable<int> GameDateId { get; set; }
        public Nullable<int> ArcId { get; set; }
    
        public virtual ICollection<Post> Posts { get; set; }
        public virtual ICollection<PostOrder> PostOrders { get; set; }
        public virtual ICollection<SessionLog> SessionLogs { get; set; }
        public virtual GameDate GameDate { get; set; }
        public virtual Arc Arc { get; set; }
        public virtual ICollection<Award> Awards { get; set; }
        public virtual ICollection<AwardNomination> AwardNominations { get; set; }
        public virtual ICollection<ExperiencePoint> ExperiencePoints { get; set; }
    }
}
