//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SimpleHitPoint
    {
        public int Id { get; set; }
        public int PersonId { get; set; }
        public int HitPointTypeId { get; set; }
        public int HitPointLevelId { get; set; }
        public Nullable<System.DateTime> Purchased { get; set; }
        public int XpCost { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
