//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Warhammer.Core.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Term
    {
        public Term()
        {
            this.ExperiencePoints = new HashSet<ExperiencePoint>();
        }
    
        public int Id { get; set; }
        public int PlayerId { get; set; }
        public int PersonId { get; set; }
        public int TermNumber { get; set; }
        public Nullable<int> RolledStatId { get; set; }
        public Nullable<int> RollResultEnum { get; set; }
        public string Question { get; set; }
        public string Answer { get; set; }
        public string Outcome { get; set; }
    
        public virtual ICollection<ExperiencePoint> ExperiencePoints { get; set; }
        public virtual Person Person { get; set; }
        public virtual PersonAttribute PersonAttribute { get; set; }
        public virtual Player Player { get; set; }
    }
}
